[versions]
# Plugins
agp = "8.13.2"
hilt = "2.57.2"
# Libraries
androidx-core = "1.17.0"
androidx-core-splashscreen = "1.2.0"
androidx-activity = "1.12.2"
google-material = "1.13.0"
lifecycle = "2.10.0"
lombok = "1.18.42"
recyclerview = "1.4.0"
recyclerview-selection = "1.2.0"
rxjava = "3.1.12"
rxjava-android = "3.0.2"

[libraries]
# AndroidX
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidx-core" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
# Google Material
google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }
# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
# Lifecycle
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "lifecycle" }
lifecycle-reactivestreams = { group = "androidx.lifecycle", name = "lifecycle-reactivestreams", version.ref = "lifecycle" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
# Lombok
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
# RecyclerView
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
recyclerview-selection = { group = "androidx.recyclerview", name = "recyclerview-selection", version.ref = "recyclerview-selection" }
# RxJava
rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
rxjava-android = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxjava-android" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
