[versions]
# Plugins
agp = "8.13.2"
hilt = "2.57.2"
# Libraries
androidx-core = "1.17.0"
androidx-core-splashscreen = "1.2.0"
androidx-activity = "1.12.2"
google-material = "1.13.0"
lombok = "1.18.42"

[libraries]
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidx-core" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }